name: TVcrawl345

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '30 3 * * *'
    - cron: '00 10 * * *'
    - cron: '30 12 * * *'
    - cron: '30 13 * * *'
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.9'
           architecture: 'x64'
      
      - name: Install requirements
        run: pip install -r ./working/requirements.txt
      
      - name: Working
        run: |
          sudo cp -p ./working/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python ./working/tv.py
      
      - name: Commit files
        run: |
          git config --local user.email "32961310+wudongdefeng@users.noreply.github.com "
          git config --local user.name "github-actions[bot]"
          git commit -m "New m3u file" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.USER_TOKEN }}
           branch: ${{ github.ref }}
